###
post  http://localhost:3009/
Content-Type: application/json 

{
    "date":"2023-01-1",
    "number":1,
    "amount":2000,
    "id":"1"

}


###
get http://localhost:3009/invoices


###
put  http://localhost:3009/1
Content-Type: application/json 

{
    "date":"2020-10-20",
    "number":10,
    "amount":2000,
    "id":"1"

}

###
delete http://localhost:3009/2


###
get http://localhost:3009/filter?financialYear=2022-23&invoiceNumber=1&startDate=2022-07-01&endDate=2022-07-31
