###
post  http://localhost:3009/
Content-Type: application/json 

{
  "date": "2020-07-15",
  "number": 1,
  "amount": 1000
}


###
get http://localhost:3009/invoices


###
put  http://localhost:3009/1
Content-Type: application/json 

{
    "date":"2021-07-04",
    "number":4,
    "amount":5000,
    "id":"2"

}

###
delete http://localhost:3009/12


###
get http://localhost:3009/filter?financialYear=2022-23&invoiceNumber=1&startDate=2022-07-01&endDate=2022-07-31
